# Generated by Django 4.2.9 on 2024-02-12 15:25

import PetstagramWorkshop101.photos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='images', validators=[PetstagramWorkshop101.photos.validators.validate_file_size]),
        ),
    ]
