# Generated by Django 4.2.10 on 2024-02-08 11:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(2)])),
                ('last_name', models.CharField(max_length=35, validators=[django.core.validators.MinLengthValidator(2)])),
                ('age', models.IntegerField()),
            ],
        ),
    ]
