# Generated by Django 4.2.10 on 2024-02-23 16:31

import Fruitipedia_app_exam_prep_2.profiles.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=25, validators=[django.core.validators.MinLengthValidator(2), Fruitipedia_app_exam_prep_2.profiles.validators.name_validator]),
        ),
    ]
